package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.43

import (
	"context"
	"fmt"
	"github.com/samber/lo"

	database "github.com/tomhaerter/course-recommender/internal/db"
	"github.com/tomhaerter/course-recommender/internal/graph/model"
)

// CreateTodo is the resolver for the createTodo field.
func (r *mutationResolver) CreateTodo(ctx context.Context, input model.NewTodo) (*database.Todo, error) {
	todo, err := r.DB.CreateTodo(ctx, input.Text)
	return &todo, err
}

// Todos is the resolver for the todos field.
func (r *queryResolver) Todos(ctx context.Context) ([]*database.Todo, error) {
	todos, err := r.DB.ListTodos(ctx)
	return lo.ToSlicePtr(todos), err
}

// CreatedAt is the resolver for the createdAt field.
func (r *todoResolver) CreatedAt(ctx context.Context, obj *database.Todo) (string, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}

// User is the resolver for the user field.
func (r *todoResolver) User(ctx context.Context, obj *database.Todo) (*model.User, error) {
	panic(fmt.Errorf("not implemented: User - user"))
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Todo returns TodoResolver implementation.
func (r *Resolver) Todo() TodoResolver { return &todoResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type todoResolver struct{ *Resolver }
