// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package database

import (
	"context"
)

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (text) VALUES ($1) RETURNING id, text, done
`

func (q *Queries) CreateTodo(ctx context.Context, text string) (Todo, error) {
	row := q.db.QueryRow(ctx, createTodo, text)
	var i Todo
	err := row.Scan(&i.ID, &i.Text, &i.Done)
	return i, err
}

const listTodos = `-- name: ListTodos :many
SELECT id, text, done FROM todos
`

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.Query(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Text, &i.Done); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
